---
- hosts: "all"
  become: true
  tasks:
  - name: "Copy our lending to /var/www/html folder"
    ansible.builtin.copy:
      src: "/home/ansible/files/index.html/"
      dest: "/var/www/index.html"
