---
- hosts: "all"
  tasks:
  - name: "Delete /var/www/html folder"
    ansible.builtin.file:
      path: "/var/www/html"
      state: "absent"

  - name: "Copy our lending to /var/www/html folder"
    copy:
      src: "/home/ansible/files/index.html/"
      dest: "/var/www/"
   
